/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:a1685816-70de-4f61-b74c-4eae7add4491",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_MCuBAD9cL",
    "aws_user_pools_web_client_id": "667kg9cgufdsauj927odjl2d66",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://yiklwswuh5avrpibuvsuivsixe.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
